# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Acerca de',   url: 'about.html'}
- {name: 'Notas y recursos', url: 'writing.html'}
- {name: 'Contacto', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/rober-mat'}
- {icon: 'twitter',    link: 'https://x.com/benroberto'}
#- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope',   link: 'mailto:rben@campus.ungs.edu.ar'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}
#- {icon: 'researchgate',   link: 'https://www.researchgate.net/profile/Roberto-Ben'}

# Customize site text
pagination:
  next_page: 'Más nuevo'
  previous_page: 'Más viejo'

sharing_button_prompt: 'Compartir!'

related_posts: 'Podría interesarte también:'

post_date_prefix: 'Escrito el'
